/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import * as apollo from "apollo-server-express";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { CreateAdministratorArgs } from "./CreateAdministratorArgs";
import { UpdateAdministratorArgs } from "./UpdateAdministratorArgs";
import { DeleteAdministratorArgs } from "./DeleteAdministratorArgs";
import { AdministratorFindManyArgs } from "./AdministratorFindManyArgs";
import { AdministratorFindUniqueArgs } from "./AdministratorFindUniqueArgs";
import { Administrator } from "./Administrator";
import { AdministratorService } from "../administrator.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Administrator)
export class AdministratorResolverBase {
  constructor(
    protected readonly service: AdministratorService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Administrator",
    action: "read",
    possession: "any",
  })
  async _administratorsMeta(
    @graphql.Args() args: AdministratorFindManyArgs
  ): Promise<MetaQueryPayload> {
    const results = await this.service.count({
      ...args,
      skip: undefined,
      take: undefined,
    });
    return {
      count: results,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Administrator])
  @nestAccessControl.UseRoles({
    resource: "Administrator",
    action: "read",
    possession: "any",
  })
  async administrators(
    @graphql.Args() args: AdministratorFindManyArgs
  ): Promise<Administrator[]> {
    return this.service.findMany(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Administrator, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Administrator",
    action: "read",
    possession: "own",
  })
  async administrator(
    @graphql.Args() args: AdministratorFindUniqueArgs
  ): Promise<Administrator | null> {
    const result = await this.service.findOne(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Administrator)
  @nestAccessControl.UseRoles({
    resource: "Administrator",
    action: "create",
    possession: "any",
  })
  async createAdministrator(
    @graphql.Args() args: CreateAdministratorArgs
  ): Promise<Administrator> {
    return await this.service.create({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Administrator)
  @nestAccessControl.UseRoles({
    resource: "Administrator",
    action: "update",
    possession: "any",
  })
  async updateAdministrator(
    @graphql.Args() args: UpdateAdministratorArgs
  ): Promise<Administrator | null> {
    try {
      return await this.service.update({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Administrator)
  @nestAccessControl.UseRoles({
    resource: "Administrator",
    action: "delete",
    possession: "any",
  })
  async deleteAdministrator(
    @graphql.Args() args: DeleteAdministratorArgs
  ): Promise<Administrator | null> {
    try {
      return await this.service.delete(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new apollo.ApolloError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
